<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Route_destination</name>
   <tag></tag>
   <elementGuidId>13ba6f39-7043-4020-8d15-84921ac1bf2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='destination'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.trackInput.active > input[name=&quot;destination&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Destination&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>349bd913-8463-4bb0-96f1-726c54bcf027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>destination</value>
      <webElementGuid>c07a6b45-ca80-45c5-8750-2f2b95257cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackRouteDestination</value>
      <webElementGuid>feca8448-c990-4fe1-8ca7-8213e465ae6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d0b63f1-57f5-4122-8b69-66a781b7231e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Destination </value>
      <webElementGuid>b9f7998d-8f93-44fe-9ed8-ed225fd21e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Destination </value>
      <webElementGuid>b086fe20-6d90-4357-af53-063ebfa3f820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Destination </value>
      <webElementGuid>62be0249-d7ad-49d6-9dbe-df1f330257bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0ffa5240-b3da-415c-9e9e-b4e18c20ce2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dda6e62b-af94-4cf3-9927-605d7f25b837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findRouteMain&quot;)/div[@class=&quot;flightSearchForm&quot;]/div[@class=&quot;searchOption routeSearch text_align_left&quot;]/form[@class=&quot;active&quot;]/div[@class=&quot;trackInputContainer&quot;]/div[@class=&quot;trackInput active&quot;]/input[@class=&quot;trackRouteDestination&quot;]</value>
      <webElementGuid>a8a2c48a-1a4c-42c7-b843-84fc2191f6e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='destination'])[2]</value>
      <webElementGuid>9ae53c5b-8f93-4e46-8bd0-ac4d632d8710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='findRouteMain']/div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>1fbab026-cc02-4aac-9aba-6e6785c924e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div[3]/div/input</value>
      <webElementGuid>2ae5cc00-b21d-4247-a086-8132efbb87e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'destination' and @type = 'text' and @placeholder = 'Destination ' and @title = 'Destination ']</value>
      <webElementGuid>dfb9f884-286b-4977-851e-267622952701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
