<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Route_origin</name>
   <tag></tag>
   <elementGuidId>3e34a649-43e0-4877-8383-831a830b8ca1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='origin'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.trackInput.active > input[name=&quot;origin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Origin&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3091f5a4-a241-4ef4-8243-336c7c2a0d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>10c34627-13f4-4db6-9bc7-03164816d139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trackRouteOrigin</value>
      <webElementGuid>2dc22556-abf5-4d50-80cf-d02b41f5e640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6cbbd6c0-275f-4b1d-b452-23269cc0b42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>df2d619e-d86a-4315-b508-8fda938a4b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>6e33423e-b956-48b1-8c6f-be26a9aee920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Origin</value>
      <webElementGuid>9816ed28-6d47-43c6-a626-8a6a2546f231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3148bc33-2c1d-4861-8648-0d1ad781ab1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b90db341-67b5-4b84-85c5-731515e4bf0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;findRouteMain&quot;)/div[@class=&quot;flightSearchForm&quot;]/div[@class=&quot;searchOption routeSearch text_align_left&quot;]/form[@class=&quot;active&quot;]/div[@class=&quot;trackInputContainer&quot;]/div[@class=&quot;trackInput active&quot;]/input[@class=&quot;trackRouteOrigin&quot;]</value>
      <webElementGuid>e2ea65d3-259b-4fc1-b58d-22694432b610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='origin'])[2]</value>
      <webElementGuid>139eac3f-97fd-4bb2-a196-e20cf2494b61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='findRouteMain']/div[2]/div/form/div/div/input</value>
      <webElementGuid>ac83898a-6648-4b10-a6ed-ca0062e6b67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div/input</value>
      <webElementGuid>c0e264f7-fb4b-458d-9d03-0d86e6938970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'origin' and @type = 'text' and @placeholder = 'Origin' and @title = 'Origin']</value>
      <webElementGuid>cfe4eef5-292a-4840-8159-4371b9229865</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
